// Catalogue of every format the app knows about. Engines decide what is actually convertible.

export const CATEGORIES = [
  { id: 'image', label: 'Image' },
  { id: 'vector', label: 'Vector' },
  { id: 'video', label: 'Video' },
  { id: 'audio', label: 'Audio' },
  { id: 'document', label: 'Document' },
  { id: 'ebook', label: 'Ebook' },
  { id: 'spreadsheet', label: 'Spreadsheet' },
  { id: 'presentation', label: 'Presentation' },
  { id: 'data', label: 'Data' },
  { id: 'archive', label: 'Archive' },
  { id: 'font', label: 'Font' },
  { id: 'subtitle', label: 'Subtitle' },
  { id: 'model', label: '3D model' },
];

const F = (category, name) => ({ category, name });

export const FORMATS = {
  // Images
  jpg: F('image', 'JPEG image'),
  jfif: F('image', 'JPEG File Interchange (JFIF)'),
  png: F('image', 'Portable Network Graphics'),
  webp: F('image', 'WebP image'),
  avif: F('image', 'AV1 image'),
  gif: F('image', 'Graphics Interchange Format'),
  tiff: F('image', 'Tagged Image File'),
  heic: F('image', 'High Efficiency Image (Apple)'),
  bmp: F('image', 'Windows bitmap'),
  ico: F('image', 'Windows icon'),
  psd: F('image', 'Photoshop document'),
  tga: F('image', 'Truevision TGA'),
  dds: F('image', 'DirectDraw surface'),
  exr: F('image', 'OpenEXR HDR image'),
  hdr: F('image', 'Radiance HDR image'),
  jp2: F('image', 'JPEG 2000'),
  pcx: F('image', 'PC Paintbrush'),
  ppm: F('image', 'Portable pixmap'),
  pgm: F('image', 'Portable graymap'),
  pbm: F('image', 'Portable bitmap'),
  pam: F('image', 'Portable arbitrary map'),
  pfm: F('image', 'Portable float map'),
  qoi: F('image', 'Quite OK Image'),
  sgi: F('image', 'Silicon Graphics image'),
  xbm: F('image', 'X bitmap'),
  xpm: F('image', 'X pixmap'),
  xwd: F('image', 'X window dump'),
  dpx: F('image', 'Digital Picture Exchange'),
  ras: F('image', 'Sun raster'),
  apng: F('image', 'Animated PNG'),
  jxl: F('image', 'JPEG XL'),
  cr2: F('image', 'Canon RAW'),
  cr3: F('image', 'Canon RAW 3'),
  nef: F('image', 'Nikon RAW'),
  arw: F('image', 'Sony RAW'),
  dng: F('image', 'Digital negative'),
  orf: F('image', 'Olympus RAW'),
  rw2: F('image', 'Panasonic RAW'),
  raf: F('image', 'Fujifilm RAW'),
  pef: F('image', 'Pentax RAW'),
  nrw: F('image', 'Nikon RAW (compact)'),
  srw: F('image', 'Samsung RAW'),
  x3f: F('image', 'Sigma RAW'),
  erf: F('image', 'Epson RAW'),
  kdc: F('image', 'Kodak RAW'),
  mrw: F('image', 'Minolta RAW'),
  '3fr': F('image', 'Hasselblad RAW'),
  iiq: F('image', 'Phase One RAW'),
  xcf: F('image', 'GIMP image'),
  cur: F('image', 'Windows cursor'),
  pict: F('image', 'Apple PICT'),
  wbmp: F('image', 'Wireless bitmap'),
  mng: F('image', 'Multiple-image PNG'),
  fits: F('image', 'FITS astronomy image'),
  dcm: F('image', 'DICOM medical image'),

  // Vector
  svg: F('vector', 'Scalable Vector Graphics'),
  eps: F('vector', 'Encapsulated PostScript'),
  ps: F('vector', 'PostScript'),
  emf: F('vector', 'Enhanced metafile'),
  wmf: F('vector', 'Windows metafile'),
  odg: F('vector', 'OpenDocument drawing'),
  vsdx: F('vector', 'Visio drawing'),
  vsd: F('vector', 'Visio 2003 drawing'),
  cdr: F('vector', 'CorelDRAW drawing'),
  dxf: F('vector', 'AutoCAD DXF drawing'),
  wpg: F('vector', 'WordPerfect graphic'),
  sxd: F('vector', 'OpenOffice.org 1 drawing'),

  // Video
  mp4: F('video', 'MPEG-4 video'),
  mkv: F('video', 'Matroska video'),
  webm: F('video', 'WebM video'),
  mov: F('video', 'QuickTime movie'),
  avi: F('video', 'Audio Video Interleave'),
  wmv: F('video', 'Windows Media Video'),
  flv: F('video', 'Flash video'),
  mpeg: F('video', 'MPEG-1/2 video'),
  m4v: F('video', 'iTunes video'),
  '3gp': F('video', '3GPP mobile video'),
  '3g2': F('video', '3GPP2 mobile video'),
  ogv: F('video', 'Ogg Theora video'),
  ts: F('video', 'MPEG transport stream'),
  mts: F('video', 'AVCHD video'),
  m2ts: F('video', 'Blu-ray BDAV video'),
  vob: F('video', 'DVD video object'),
  asf: F('video', 'Advanced Systems Format'),
  f4v: F('video', 'Flash MP4 video'),
  mxf: F('video', 'Material Exchange Format'),
  rm: F('video', 'RealMedia'),
  rmvb: F('video', 'RealMedia VBR'),
  divx: F('video', 'DivX video'),
  y4m: F('video', 'YUV4MPEG2 raw video'),
  dv: F('video', 'Digital Video'),
  nut: F('video', 'NUT container'),
  ivf: F('video', 'IVF (VP8/VP9/AV1) stream'),
  h264: F('video', 'Raw H.264 stream'),
  hevc: F('video', 'Raw H.265 stream'),
  wtv: F('video', 'Windows recorded TV'),

  // Audio
  mp3: F('audio', 'MP3 audio'),
  wav: F('audio', 'Waveform audio'),
  flac: F('audio', 'Free Lossless Audio Codec'),
  aac: F('audio', 'Advanced Audio Coding'),
  m4a: F('audio', 'MPEG-4 audio'),
  m4b: F('audio', 'MPEG-4 audiobook'),
  ogg: F('audio', 'Ogg Vorbis audio'),
  opus: F('audio', 'Opus audio'),
  wma: F('audio', 'Windows Media Audio'),
  aiff: F('audio', 'Audio Interchange File'),
  ac3: F('audio', 'Dolby Digital'),
  eac3: F('audio', 'Dolby Digital Plus'),
  dts: F('audio', 'DTS audio'),
  amr: F('audio', 'Adaptive Multi-Rate'),
  mka: F('audio', 'Matroska audio'),
  weba: F('audio', 'WebM audio'),
  caf: F('audio', 'Core Audio Format'),
  au: F('audio', 'Sun audio'),
  mp2: F('audio', 'MPEG layer II audio'),
  wv: F('audio', 'WavPack'),
  ape: F('audio', "Monkey's Audio"),
  tta: F('audio', 'True Audio'),
  spx: F('audio', 'Speex'),
  mpc: F('audio', 'Musepack'),
  voc: F('audio', 'Creative Voice'),
  w64: F('audio', 'Sony Wave64'),
  ra: F('audio', 'RealAudio'),
  gsm: F('audio', 'GSM audio'),
  mid: F('audio', 'MIDI'),
  m4r: F('audio', 'iPhone ringtone'),
  mod: F('audio', 'Amiga tracker module'),
  xm: F('audio', 'FastTracker 2 module'),
  it: F('audio', 'Impulse Tracker module'),
  s3m: F('audio', 'Scream Tracker 3 module'),

  // Documents
  pdf: F('document', 'Portable Document Format'),
  docx: F('document', 'Word document'),
  doc: F('document', 'Word 97-2003 document'),
  docm: F('document', 'Word macro document'),
  dotx: F('document', 'Word template'),
  odt: F('document', 'OpenDocument text'),
  ott: F('document', 'OpenDocument text template'),
  rtf: F('document', 'Rich Text Format'),
  txt: F('document', 'Plain text'),
  md: F('document', 'Markdown'),
  html: F('document', 'Web page'),
  xhtml: F('document', 'XHTML page'),
  mhtml: F('document', 'Web archive'),
  tex: F('document', 'LaTeX'),
  rst: F('document', 'reStructuredText'),
  org: F('document', 'Emacs Org mode'),
  adoc: F('document', 'AsciiDoc'),
  textile: F('document', 'Textile'),
  wiki: F('document', 'MediaWiki markup'),
  ipynb: F('document', 'Jupyter notebook'),
  typ: F('document', 'Typst'),
  opml: F('document', 'Outline (OPML)'),
  xps: F('document', 'XML Paper Specification'),
  oxps: F('document', 'Open XML Paper'),
  wpd: F('document', 'WordPerfect'),
  wps: F('document', 'Microsoft Works'),
  pages: F('document', 'Apple Pages'),
  abw: F('document', 'AbiWord'),
  man: F('document', 'Man page'),
  pub: F('document', 'Microsoft Publisher'),
  hwp: F('document', 'Hangul word processor'),
  sxw: F('document', 'OpenOffice.org 1 text'),
  wri: F('document', 'Windows Write'),

  // Ebooks
  epub: F('ebook', 'Electronic publication'),
  mobi: F('ebook', 'Mobipocket ebook'),
  azw3: F('ebook', 'Kindle ebook'),
  azw: F('ebook', 'Kindle ebook (old)'),
  fb2: F('ebook', 'FictionBook'),
  cbz: F('ebook', 'Comic book (ZIP)'),
  cbr: F('ebook', 'Comic book (RAR)'),
  lit: F('ebook', 'Microsoft Reader'),
  lrf: F('ebook', 'Sony Reader'),
  pdb: F('ebook', 'Palm ebook'),
  pml: F('ebook', 'Palm markup'),
  rb: F('ebook', 'Rocket ebook'),
  snb: F('ebook', 'Shanda Bambook'),
  tcr: F('ebook', 'Psion ebook'),
  txtz: F('ebook', 'Zipped text ebook'),
  htmlz: F('ebook', 'Zipped HTML ebook'),
  chm: F('ebook', 'Compiled HTML Help'),
  djvu: F('ebook', 'DjVu document'),

  // Spreadsheets
  xlsx: F('spreadsheet', 'Excel workbook'),
  xls: F('spreadsheet', 'Excel 97-2003 workbook'),
  xlsm: F('spreadsheet', 'Excel macro workbook'),
  xlsb: F('spreadsheet', 'Excel binary workbook'),
  ods: F('spreadsheet', 'OpenDocument spreadsheet'),
  fods: F('spreadsheet', 'Flat OpenDocument spreadsheet'),
  csv: F('spreadsheet', 'Comma-separated values'),
  tsv: F('spreadsheet', 'Tab-separated values'),
  numbers: F('spreadsheet', 'Apple Numbers'),
  dbf: F('spreadsheet', 'dBASE table'),
  slk: F('spreadsheet', 'Symbolic link (SYLK)'),
  dif: F('spreadsheet', 'Data Interchange Format'),
  wk1: F('spreadsheet', 'Lotus 1-2-3'),
  wks: F('spreadsheet', 'Lotus / Works sheet'),
  qpw: F('spreadsheet', 'Quattro Pro'),
  sxc: F('spreadsheet', 'OpenOffice.org 1 spreadsheet'),

  // Presentations
  pptx: F('presentation', 'PowerPoint presentation'),
  ppt: F('presentation', 'PowerPoint 97-2003'),
  ppsx: F('presentation', 'PowerPoint show'),
  pps: F('presentation', 'PowerPoint 97-2003 show'),
  odp: F('presentation', 'OpenDocument presentation'),
  key: F('presentation', 'Apple Keynote'),
  sxi: F('presentation', 'OpenOffice.org 1 presentation'),

  // Data
  json: F('data', 'JSON'),
  jsonl: F('data', 'JSON Lines'),
  yaml: F('data', 'YAML'),
  xml: F('data', 'XML'),
  toml: F('data', 'TOML'),
  ini: F('data', 'INI configuration'),
  plist: F('data', 'Property list'),

  // Archives
  zip: F('archive', 'ZIP archive'),
  '7z': F('archive', '7-Zip archive'),
  rar: F('archive', 'RAR archive'),
  tar: F('archive', 'Tape archive'),
  'tar.gz': F('archive', 'Gzipped tarball'),
  'tar.bz2': F('archive', 'Bzip2 tarball'),
  'tar.xz': F('archive', 'XZ tarball'),
  gz: F('archive', 'Gzip'),
  bz2: F('archive', 'Bzip2'),
  xz: F('archive', 'XZ'),
  iso: F('archive', 'Disk image'),
  cab: F('archive', 'Windows cabinet'),
  wim: F('archive', 'Windows imaging'),
  lzh: F('archive', 'LHA archive'),
  arj: F('archive', 'ARJ archive'),
  cpio: F('archive', 'CPIO archive'),
  rpm: F('archive', 'RPM package'),
  deb: F('archive', 'Debian package'),
  jar: F('archive', 'Java archive'),
  apk: F('archive', 'Android package'),
  z: F('archive', 'Unix compress'),
  zst: F('archive', 'Zstandard'),
  lz: F('archive', 'Lzip'),
  lzma: F('archive', 'LZMA'),
  dmg: F('archive', 'macOS disk image'),
  vhd: F('archive', 'Virtual hard disk'),
  vhdx: F('archive', 'Hyper-V virtual disk'),
  vmdk: F('archive', 'VMware virtual disk'),
  msi: F('archive', 'Windows installer'),
  xar: F('archive', 'XAR archive'),
  squashfs: F('archive', 'SquashFS image'),

  // Fonts
  ttf: F('font', 'TrueType font'),
  otf: F('font', 'OpenType font'),
  woff: F('font', 'Web Open Font'),
  woff2: F('font', 'Web Open Font 2'),
  eot: F('font', 'Embedded OpenType'),

  // Subtitles
  srt: F('subtitle', 'SubRip subtitles'),
  vtt: F('subtitle', 'WebVTT subtitles'),
  ass: F('subtitle', 'Advanced SubStation'),
  ssa: F('subtitle', 'SubStation Alpha'),
  lrc: F('subtitle', 'Lyrics (LRC)'),
  ttml: F('subtitle', 'Timed Text Markup'),
  sub: F('subtitle', 'MicroDVD subtitles'),
  smi: F('subtitle', 'SAMI subtitles'),
  scc: F('subtitle', 'Scenarist closed captions'),
  mpl: F('subtitle', 'MPL2 subtitles'),

  // 3D models
  stl: F('model', 'STL 3D model'),
  obj: F('model', 'Wavefront OBJ'),
  ply: F('model', 'Polygon file (PLY)'),
  gltf: F('model', 'glTF 2.0 (JSON)'),
  glb: F('model', 'glTF 2.0 binary'),
  fbx: F('model', 'Autodesk FBX'),
  dae: F('model', 'COLLADA'),
  '3ds': F('model', '3D Studio'),
  '3mf': F('model', '3D Manufacturing Format'),
  off: F('model', 'Object File Format'),
  x3d: F('model', 'X3D scene'),
};

// Output spellings that are the same bytes as another format with a different
// extension: convert to the canonical format, then name the file this way.
export const OUTPUT_ALIASES = { jfif: 'jpg', m4r: 'm4a' };

// Input spellings that map to a canonical format.
export const ALIASES = {
  jpeg: 'jpg', jpe: 'jpg', jfif: 'jpg', pjpeg: 'jpg',
  tif: 'tiff',
  heif: 'heic', hif: 'heic',
  j2k: 'jp2', jpf: 'jp2', jpx: 'jp2', j2c: 'jp2',
  pnm: 'ppm', icb: 'tga', vda: 'tga', vst: 'tga', sun: 'ras',
  htm: 'html', shtml: 'html', mht: 'mhtml',
  markdown: 'md', mdown: 'md', mkd: 'md', mkdn: 'md', text: 'txt', log: 'txt', latex: 'tex', asciidoc: 'adoc', mediawiki: 'wiki',
  yml: 'yaml', ndjson: 'jsonl',
  mpg: 'mpeg', mpe: 'mpeg', m1v: 'mpeg', m2v: 'mpeg', qt: 'mov', '3gpp': '3gp', ogm: 'ogv', xvid: 'avi', m2t: 'ts', mod: 'mpeg', tod: 'mpeg', '264': 'h264', avc: 'h264', '265': 'hevc', h265: 'hevc',
  aif: 'aiff', aifc: 'aiff', oga: 'ogg', mpga: 'mp3', snd: 'au', mpp: 'mpc', midi: 'mid', ram: 'ra',
  tgz: 'tar.gz', taz: 'tar.gz', tbz: 'tar.bz2', tbz2: 'tar.bz2', tb2: 'tar.bz2', txz: 'tar.xz', gzip: 'gz', bzip2: 'bz2', '7zip': '7z', lha: 'lzh',
  pot: 'ppt', potx: 'pptx', xlt: 'xls', xltx: 'xlsx', dot: 'doc', ots: 'ods', otp: 'odp',
  prc: 'mobi', kf8: 'azw3', cb7: 'cbz',
  dfont: 'ttf',
  dxfp: 'ttml', dfxp: 'ttml',
  m4r: 'm4a', mptm: 'it', umx: 'mod', mo3: 'mod', mtm: 'mod', '669': 'mod',
  ai: 'pdf', svgz: 'svg', dcm30: 'dcm', dicom: 'dcm', fit: 'fits', fts: 'fits', pct: 'pict', djv: 'djvu',
  pptm: 'pptx', potm: 'pptx', ppsm: 'ppsx', xltm: 'xlsx', dotm: 'docx', vsdm: 'vsdx', vdx: 'vsd',
  kml: 'xml', gpx: 'xml', rss: 'xml', atom: 'xml', xsd: 'xml', xsl: 'xml', xslt: 'xml', svc: 'xml', resx: 'xml',
  geojson: 'json', har: 'json', webmanifest: 'json', properties: 'ini', cfg: 'ini', conf: 'ini', env: 'ini',
  war: 'zip', ear: 'zip', whl: 'zip', nupkg: 'zip', xpi: 'zip', ipa: 'zip', aar: 'zip', appx: 'zip', msix: 'zip', vsix: 'zip', kmz: 'zip', sketch: 'zip',
  tlz: 'lz', img: 'iso', udf: 'iso', sqsh: 'squashfs', snap: 'squashfs',
  sami: 'smi', mpl2: 'mpl',
  gltf2: 'gltf', stla: 'stl', stlb: 'stl',
};

/** Detect the canonical format of a filename (handles compound extensions like .tar.gz). */
export function detectFormat(filename) {
  const lower = String(filename || '').toLowerCase().trim();
  const compound = lower.match(/\.(tar\.(gz|bz2|xz|zst))$/);
  if (compound) return compound[1] === 'tar.zst' ? 'zst' : compound[1];
  const m = lower.match(/\.([a-z0-9]{1,12})$/);
  if (!m) return '';
  const ext = m[1];
  return ALIASES[ext] || ext;
}

export const categoryOf = (fmt) => FORMATS[fmt]?.category || null;
